### ISSUE TITLE
Issue with '@' symbol in password while connecting through SFTP

### ISSUE THREAD

**Issue by rakeshgeci** [fracpete/vfsjfilechooser2#6]
Click on Connections in open window, make an sftp connection in which the password field contains symbol "@". When clicked on connect an error dialog is opened with no error message.

Note: will works fine if %40 is used instead of @

**Comment by fracpete** [comment]
Thanks for the bug report. The project is no longer actively developed, but I've released a new version nonetheless which should fix this issue: 0.2.8.
